## Get gdelt dataset

In [9]:
import pandas as pd
import os

In [10]:
PATH_CITIES = '../../cities.csv'
PATH = 'Data/'

### Merge data

#### Get cities

In [11]:
cities = pd.read_csv('../../cities.csv')
cities

       lat      lng   Municipality  Municipality code     ISO
0   6.2447 -75.5748       Medellín               5001  CO-ANT
1   3.4400 -76.5197           Cali              76001  CO-VAC
2   4.5781 -74.2144         Soacha              25754  CO-CUN
3   4.1425 -73.6294  Villavicencio              50001  CO-MET
4   1.2136 -77.2811          Pasto              52001  CO-NAR
5  10.9639 -74.7964   Barranquilla               8001  CO-ATL
6   7.1186 -73.1161    Bucaramanga              68001  CO-SAN
7   4.4378 -75.2006         Ibagué              73001  CO-TOL
8   2.4411 -76.6061        Popayán              19001  CO-CAU
9   7.9075 -72.5047         Cúcuta              54001  CO-NSA

#### Get datasets

In [22]:
df = pd.DataFrame()
for city in os.listdir(PATH):
    if city.endswith('.csv'):
        city_path = os.path.join(PATH, city)
        df_aux = pd.read_csv(city_path)
        df_aux['Municipality code'] = city.replace('.csv', '')
        df = pd.concat([df, df_aux], ignore_index=True)
        
df

,GLOBALEVENTID,SQLDATE,MonthYear,Year,Actor1Name,Actor1CountryCode,Actor2Name,Actor2CountryCode,EventCode,NumMentions,NumSources,NumArticles,AvgTone,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,SOURCEURL,Municipality code
0,467522672,20150916,201509,2015,COLOMBIA,COL,RADIO STATION,NaN,193,4,1,4,-3.030303,CO,CO19,4.23161,-73.5079,10864086,http://www.unmultimedia.org/radio/english/2015...,Villavicencio
1,465775735,20150911,201509,2015,GUNMAN,NaN,COLOMBIA,COL,193,6,2,6,-5.497685,CO,CO19,4.23161,-73.5079,10864086,http://www.nzherald.co.nz/world/news/article.c...,Villavicencio
2,459806479,20150821,201508,2015,COLOMBIAN,COL,NaN,NaN,186,14,6,14,-2.199586,CO,CO19,4.00000,-73.3667,-589367,http://globenewswire.com/news-release/2015/08/...,Villavicencio
3,520388626,20160312,201603,2016,COLOMBIA,COL,JOURNALIST,NaN,193,2,1,2,-8.240535,CO,CO19,4.23161,-73.5079,10864086,http://www.dailystar.co.uk/news/latest-news/50...,Villavicencio
4,496403031,20151222,201512,2015,GOVERNMENT,NaN,COLOMBIA,COL,190,1,1,1,-5.557300,CO,CO19,4.32900,-72.8381,-590973,http://www.offnews.info/verArticulo.php?conten...,Villavicencio
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31056,954996616,20201118,202011,2020,HONDURAS,HND,NaN,NaN,192,8,1,8,-5.488621,CO,CO21,8.80389,-72.9536,29198,https://www.marshallindependent.com/news/inter...,Cúcuta
31057,955046947,20201118,202011,2020,PRESIDENT,NaN,NaN,NaN,190,3,1,3,-4.580153,CO,CO21,8.80389,-72.9536,29198,https://colombiareports.com/colombia-rescues-d...,Cúcuta
31058,956040249,20201124,202011,2020,TOURIST,NaN,NaN,NaN,193,2,1,2,-2.453271,CO,CO21,8.80389,-72.9536,29198,https://www.laprensalatina.com/iota-deals-anot...,Cúcuta
31059,962369859,20210102,202101,2021,CARRIER,NaN,NaN,NaN,190,5,1,5,-1.003344,CO,CO21,8.27556,-72.3958,230744,https://www.flightglobal.com/safety/avianca-a3...,Cúcuta
31060,955052962,20201118,202011,2020,INDIGENOUS,NaN,PANAMA,PAN,190,6,2,6,-6.432749,CO,CO21,8.80389,-72.9536,29198,https://tucson.com/news/world/hurricane-iota-b...,Cúcuta

In [24]:
df.to_csv('labels.csv', index=False)